language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # FTP_USER
    - secure: "FK6GI6X7g+x4e/cCiBV6rG1HkjEVO9t3p4Yh8LK4v9kOo2lPAnk8yHIxk6upz9XUd+vWEdIHcqDcKBiXZwhAKU+7FrPluLEE+qg/2hhWn2m7FriGua5ekUmSNar0dqe0o9qaZtQUkwzDdeV0JTnJ575H4853vVBnE/fiwLP/TNwGbgHScm0QydaEs8V1AyzYTq5Eln3Rs4sbkzbolww1YLDGobzTUajKHuu+HbcKvmp4yX8f7F5V7JDa0nY8IWE/6igon3HX3RkbMSeyB0XqbN6srpffAH/GxOE3El9tCfa5ySyfV4riGVHHqfx9jNYi/lGYGT+UuydRQk3DJsi34+bzKNiGs/vwBS8jv53uVDZ5V+U51usxVVGAxQBY3kbtC3ArtoANSTss8q1pOExmNdgvi9qsvHJNRj2fAqFRQBcNG7/bcZSz5ECUgpsWOtOdCyL23i658YngfACDeEidal3zZJstesp1cVk/0xSTVF4jSSIGk3kHGwRNOBx+JL8dbF9x9CWPqSm8t4YO8d6pAmnhHP+3K4UMjgQkWBlZIu7Rtcgv03mU4KM4hpRjcsbbuVlheLWQhR9keUJGsEyUjLtsbmdMR4RXJ1zydovTNJ9zTw4QMJdhsvLT4c7hbcgJ1YaCTeoKm3UQI/Cjkx4DDJcx2Vy93tCsjEOz9Fa96CM="
    # FTP_PASSWORD
    - secure: "3Jm4jrjDmgqLKa79UgWx8hpPSgbKp+e+SZNOc3SroP1HB1TgNI7NaLM4FFgBBb7ztL3BVFAW9Q7x2ynPyWm+8wqN+mvxbCZCeZ5jiE4z4/CBX6r1KCbxxx252kFa2lG8Dk/d++cZq18UnjKGYnTgR5NuzvAmeG0BHPkredjGfIwAzIKBM+5/ydfFl7uGR5ETOzvpMCPQlnjWgQjBMHXMGrtAq9ikKwHjXfAYIpp9GBSY5py+AYjNLsZqNICedXJwLhg5DDOeMJw3KtU8DVmqJzdIriN5hUuZ0aCGJPGBrHx0qgJ/q6CcSafpPiSpCvombrBjkJUGJcyQSSy6lmifqx4mQSQsePMwjen5ly5QqF0ugp5X0MrXqyTTTaWN7jZFKc/UDViWDyQ1YyvoIPDZMQS7hSRsXn2mNIALfqmwwd5KQ08hmay09U6v7XmvBaIhz254Eh8PhH+arDlM41DUTDNOmLPNUG7+vbxNqW+hkZzM2BjYXT1xRVJ9Lqs+LmrxtOgVntDxS4APgruL7+HYb4ov2qNwOnWEMfX826lEOC//+IjGQePESrbIRh2UeHYm8V+Jt3ZEO/4NW3xJOS46Eu2w7AbuKDvJPOcySy3jLYtqh9VjWP/wL+7hetCXMAdSo6F3Hlqyq3f4CGM134/qotiqlE95unsTbFtZR/davDE="
    # FTP_URL
    - secure: "O9LMx7pNPiRw4qzsJTJ6IRkhDNEy4SppmbAcRVPF/7EfQJdfROxOi3SVqV/b9tf3qiTJAmoC/eb0+mKOunE7Qp0JijsGHMwprZ1LVkfQCyksT9npQ5QYeQ7UCXQk9uxMwafNNpMuBSIhHnqKlXMhRpx5nEPeKINhcIrlXk4xAAkpUaUA1qr07VlyI7Sic0B0NrUTBHwA2VK3yRJLwxxisvZ3x12k3B5dNq2rNbye0V8yzS+5gYGy0OHcR4GkwBfxynIB/QJZFMto2eQ5fJ+bA2hNJeaXWGAYBfSBs3XbEOkInxxsawDnWybRpKlVZHAgFZ0+jYE+f2zPQ+D5l5tVFsNCVpORyRi4xQbciSHjTo1g50RYFY5MIOO9L7ldDl3ShmbKT0TGnu5/Vf9tEKirU2KArCXKoII9heag/iY0aHxnJ3dSm1ROIDqXru5Ik2X9kOEu/0BfZmAtgtGXF1NhER2EHKeV6n1GOOtfr+Ini0nJpkg1KOv8PWFedyKV2O+DEcGSP3b4U0fdqbWLn0NStNaJBHVakTsMxOXVJfLPPrGz+1RtmT+0pYIfn7idoIpViVH1cG56XfjS3dKIgo9GVKIpYK76PEesIzNIQzG074/nhy49ra7WLnHGfyr115QVK/jDWB61ngms3nYoh+fMUTkCbhEu2CzPmOXLDJfpz0k="

arch:
  packages:
    - qbs
    - qt5-tools
    - qt5-declarative
    - libqtxdg
    #- clazy-git
    - xorg-server-xvfb
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 qbs.installRoot:/ qbs.installPrefix:usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: curl --ftp-create-dirs -T build/default/libliri-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_URL/artifacts/master/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc"
  - provider: script
    script: curl --ftp-create-dirs -T build/default/libliri-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD $FTP_URL/artifacts/develop/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
