language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # FTP_USER
    - secure: "FK6GI6X7g+x4e/cCiBV6rG1HkjEVO9t3p4Yh8LK4v9kOo2lPAnk8yHIxk6upz9XUd+vWEdIHcqDcKBiXZwhAKU+7FrPluLEE+qg/2hhWn2m7FriGua5ekUmSNar0dqe0o9qaZtQUkwzDdeV0JTnJ575H4853vVBnE/fiwLP/TNwGbgHScm0QydaEs8V1AyzYTq5Eln3Rs4sbkzbolww1YLDGobzTUajKHuu+HbcKvmp4yX8f7F5V7JDa0nY8IWE/6igon3HX3RkbMSeyB0XqbN6srpffAH/GxOE3El9tCfa5ySyfV4riGVHHqfx9jNYi/lGYGT+UuydRQk3DJsi34+bzKNiGs/vwBS8jv53uVDZ5V+U51usxVVGAxQBY3kbtC3ArtoANSTss8q1pOExmNdgvi9qsvHJNRj2fAqFRQBcNG7/bcZSz5ECUgpsWOtOdCyL23i658YngfACDeEidal3zZJstesp1cVk/0xSTVF4jSSIGk3kHGwRNOBx+JL8dbF9x9CWPqSm8t4YO8d6pAmnhHP+3K4UMjgQkWBlZIu7Rtcgv03mU4KM4hpRjcsbbuVlheLWQhR9keUJGsEyUjLtsbmdMR4RXJ1zydovTNJ9zTw4QMJdhsvLT4c7hbcgJ1YaCTeoKm3UQI/Cjkx4DDJcx2Vy93tCsjEOz9Fa96CM="
    # FTP_PASSWORD
    - secure: "3Jm4jrjDmgqLKa79UgWx8hpPSgbKp+e+SZNOc3SroP1HB1TgNI7NaLM4FFgBBb7ztL3BVFAW9Q7x2ynPyWm+8wqN+mvxbCZCeZ5jiE4z4/CBX6r1KCbxxx252kFa2lG8Dk/d++cZq18UnjKGYnTgR5NuzvAmeG0BHPkredjGfIwAzIKBM+5/ydfFl7uGR5ETOzvpMCPQlnjWgQjBMHXMGrtAq9ikKwHjXfAYIpp9GBSY5py+AYjNLsZqNICedXJwLhg5DDOeMJw3KtU8DVmqJzdIriN5hUuZ0aCGJPGBrHx0qgJ/q6CcSafpPiSpCvombrBjkJUGJcyQSSy6lmifqx4mQSQsePMwjen5ly5QqF0ugp5X0MrXqyTTTaWN7jZFKc/UDViWDyQ1YyvoIPDZMQS7hSRsXn2mNIALfqmwwd5KQ08hmay09U6v7XmvBaIhz254Eh8PhH+arDlM41DUTDNOmLPNUG7+vbxNqW+hkZzM2BjYXT1xRVJ9Lqs+LmrxtOgVntDxS4APgruL7+HYb4ov2qNwOnWEMfX826lEOC//+IjGQePESrbIRh2UeHYm8V+Jt3ZEO/4NW3xJOS46Eu2w7AbuKDvJPOcySy3jLYtqh9VjWP/wL+7hetCXMAdSo6F3Hlqyq3f4CGM134/qotiqlE95unsTbFtZR/davDE="
    # ARTIFACTS_HOST
    - secure: "xWzpYCJoPoOLcPuA4nEtelqaSckkGrPhWyL8f85PmLJB7NIIn9jSSQHX545se4jTdJsdcqiko1JTblQzsjr8bik7OBghcckicx4tOnv5e7Xb9FPx6eQMm/uGDPkSYug2lcjXKthoC7TLa2pk1MnwNCvO2/JMIVerZjH5ETOIAA8y30XnPNJlRyPpQY7kMUU7tx1vH1xZawvGfBqEGMx+Y2cGSyuIOn3TG1LCKxhCZBk0X1mgxQLBrQHn+lzoEJBUpcIsNHYcDLUFq0+jUdsD4z+E9vKRIL0U1d53BEHCXf97Ay2f/BU3Z9exLQVS9pGtYiLMhjcX9MWgZBNWZlPmJI7fA+AmMVRemp4EtNNKkcobRFnjBJRFTknsPCUYkrRoGoWg0Icr0UBV+rgW0NKZ6X79D0O1yVvO7/O+MkwStCjkuiH93HEuJkO541hIvMNH7qonGgBIVjPbkfKlKuuC11eCPiV2LlUw1Y/FgdcJhSPZIId5R0BuLJCl2I2Way83e353Qnij3kUwWbFRumZ8f5mCpItWAJP2eAhalJy49ZIGZoqmhWg994gahFpCu4wfqktoG51kiYpeDPavZPMWeY/PZcwHfMtTfoBH4LW0mu49t22GCdh6gqAtAJXZg3gA3lb8XbtyvOq8c9TNgRcXjRQvGl1BzqTXcIRcYtMzXg4="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
    - qt5-tools
    - qt5-declarative
    - libqtxdg
    #- clazy-git
    - xorg-server-xvfb
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 modules.qbs.installRoot:/ modules.lirideployment.prefix:/usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: curl --ftp-create-dirs -T build/default/libliri-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://$ARTIFACTS_HOST/artifacts/master/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc"
  - provider: script
    script: curl --ftp-create-dirs -T build/default/libliri-artifacts.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://$ARTIFACTS_HOST/artifacts/develop/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
